blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import PostSiteMap

sitemaps = {
    'posts': PostSiteMap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('main.urls', namespace='main')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='from django.contrib.sitemaps.views.sitemap'
    )
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.posts_list, name='posts_list'),
    path('tag/<slug:tag_slug>/', views.posts_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='posts_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.get_post, name='get_post'
         ),
    path('<int:post_id>/share/', views.post_share, name='share_post'),
    path('search/', views.post_search, name='post_search')
]

main/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager

STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published')
)


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager, self) \
            .get_queryset() \
            .filter(status='published')


class Post(models.Model):
    tags = TaggableManager()
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = RichTextField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:get_post', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=8)
    email = models.EmailField()
    body = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

main/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'post/list.html'


def posts_list(request, tag_slug=None):
    db_posts = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        db_posts = db_posts.filter(tags__in=[tag])

    paginator = Paginator(db_posts, 3)
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page_number,
        'posts': posts,
        'tag': tag
    }

    return render(request, 'post/list.html', context)


def get_post(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published \
                        .filter(tags__in=post_tags_ids) \
                        .exclude(id=post.id) \
                        .annotate(shared_tags=Count('tags')) \
                        .order_by('-shared_tags', '-publish')[:4]

    if request.method == 'POST':
        # Create new comment
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts
    }
    return render(request, 'post/detail.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Send mail
            form_data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'Hello!, {form_data["name"]} recommends you read {post.title}'
            message = f'Read {post.title} at {post_url}\n\n {form_data["name"]}\'s comments: {form_data["comments"]}'
            send_mail(subject, message, 'mailknightsarai@gmail.com', [form_data['to']])
            sent = True

    else:
        form = EmailPostForm()

    return render(request, 'post/share.html', {
        'post': post,
        'form': form,
        'sent': sent
    })


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.2).order_by('-rank')
    return render(
        request,
        'post/search.html',
        {
            'form': form,
            'results': results,
            'query': query
        }
    )

main/templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="eng">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}"
          rel="stylesheet"
    >
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>This is knight blog. Total posts: <strong>{% total_posts %}</strong></p>
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

main/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

main/templates/post/detail.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|safe|linebreaks }}
    <hr>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    <hr>
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post"
              style="display: flex; flex-direction: column"
        >
            {{ comment_form.as_p }}
            {{ comment_form.media }}
            {% csrf_token %}
            <p><input type="submit"
                      value="Add comment"
            ></p>
        </form>
    {% endif %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|safe|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
{% endblock %}

main/templates/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

main/templates/post/list.html
{% extends "base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>Knight Blog</h1>
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">
            {{ post.title }}</a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "main:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|safe|truncatewords:30|linebreaks }}
        <p>
            <a href="{% url "main:share_post" post.id %}">
                Share this post
            </a>
        </p>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

main/templates/post/search.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|safe|truncatewords_html:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "main:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit"
                   value="Search"
            >
        </form>
    {% endif %}
{% endblock %}

main/templates/post/share.html
{% extends "base.html" %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
{#            {% for field in form %}#}
{#                <div>#}
{#                    {{ field.errors }}#}
{#                    {{ field.label_tag }} {{ field }}#}
{#                </div>#}
{#            {% endfor %}#}
            {% csrf_token %}
            <input type="submit"
                   value="Send Mail"
            >
        </form>
    {% endif %}
{% endblock %}